name: Run tests on staging
on:
  workflow_dispatch

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Generate authentication token
        id: gen-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CVAT_BOT_APP_ID }}
          private-key: ${{ secrets.CVAT_BOT_PRIVATE_KEY }}
          repositories: "public,private"
      - uses: actions/checkout@v4
        with:
          repository: azhavoro-org/private
          token: ${{ steps.gen-token.outputs.token }}
